name : jobs mangment
on : 
    workflow_dispatch:
jobs:
    
    job1:
        runs-on: ubuntu-latest
        steps:
            -  run: echo " This is job 1 ${{github.job}}"
    
    job2:
        runs-on: ubuntu-latest
        needs: job1
        steps:
            -  run: echo " This is job 2 ${{github.job}}" 
    job3:
        runs-on: ubuntu-latest
        needs: job1
        steps:
            -  run: echo " This is job 3 ${{github.job}}"
    job4:
        runs-on: ubuntu-latest
        needs: [job2, job3]
        steps:
            -  run: echo " This is job 4 ${{github.job}}"

        