name : Manual WorkFLow
on : 
    workflow_dispatch:
        inputs:
            environment:
                description: 'Select the environment to deploy'
                required: true
                default: 'production'
                type: choice
                options:
                    - production
                    - staging
            browser:
                description: 'Select the page to deploy'
                required: true
                default: 'goooogle'
                type: choice
                options:
                    - goooogle
                    - facebook

jobs:
  deplodsay:
    runs-on: ubuntu-latest

    steps:
      - name: Print Wellcome Message
        run: echo "Welome to manual WorkFlow ✌"

        
